name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infrastucture
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
<<<<<<< HEAD
=======
      TF_VAR_REGION: ${{ secrets.TF_VAR_region }}
      TF_VAR_BUCKET_NAME:  ${{ secrets.TF_VAR_bucket_name }}
      TF_VAR_TABLE_NAME: ${{ secrets.TF_VAR_table_name }}
>>>>>>> 40dbb5e (Change in variables)

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
<<<<<<< HEAD
        run: terraform plan -lock=false
        
=======
        run: terraform plan

>>>>>>> 40dbb5e (Change in variables)
      - name: Terraform Apply
        run: terraform apply -auto-approve
