name: Destroy Website

on:
  workflow_dispatch:

jobs:
  tf-destroy:
    name: Destroy Infrastucture
    runs-on: self-hosted

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_nc_api_uname: ${{ secrets.TF_VAR_nc_api_uname }}
      TF_VAR_nc_api_key: ${{ secrets.TF_VAR_nc_api_key }}

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy Plan
        run: terraform plan -destroy
        continue-on-error: true
        
      - name: Terraform Destroy
        id: Destroy
        run: terraform destroy -auto-approve
